#!/usr/bin/env python3
# Copyright (c) ALRIGROUP and its affiliates.
#
# This code is licensed under the ARGLR - ALRI GROUP LICENSE RESERVED
# found in the LICENSE file in the root directory of this source tree
# and at: https://github.com/alrigroup/licenses/tree/main
# -*- coding: utf-8 -*-
"""ALRIOS end-to-end test suite (F1-F5).

Orchestrates: build (optional) -> TEST-mode arws config -> start arcore ->
runs F1 (control channel), F2 (autostart), F3 (CLI), F4 (app/gateway queries),
F5 (armake buildapp + redirect 302) and HTTP checks -> cleanup (restore config,
stop arcore, no orphans).

Usage: python test_suite.py [--no-build]
"""
import http.client
import os
import shutil
import socket
import struct
import subprocess
import sys
import time

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.abspath(__file__))
ARWS = os.path.join(ROOT, "arcore")
CFG = os.path.join(ARWS, "storage", "arws", "arws.cfg")
BAKCFG = os.path.join(ARWS, "storage", "arws", "arws.cfg.production")
LOG = os.path.join(ARWS, "test_suite.log")
AUTOSTART = os.path.join(ARWS, "autostart.cfg")
BAK_AUTOSTART = os.path.join(ARWS, "autostart.cfg.suitebak")

TEST_CFG_CONTENT = (
    "# ALRI Web Services Config - TEST mode (generated by test_suite)\n"
    "mode=test\n"
    "port=8080\n"
    "bind=127.0.0.1\n"
    "global_mode=production\n"
    "cache_ttl=0\n"
)

# IPC frame types (mirror ar_ipc.h)
IPC_REGISTER = 1
IPC_UNREGISTER = 2
IPC_RESPONSE = 4
IPC_ACK = 6
IPC_ERROR = 7
IPC_QUERY = 9
IPC_QUERY_RESP = 10
IPC_CTL_PING = 13
IPC_CTL_START = 14
IPC_CTL_STOP = 15
IPC_CTL_RESTART = 16
IPC_CTL_STATUS = 17
IPC_CTL_LIST = 18
IPC_CTL_POWER_OFF = 19
IPC_CTL_POWER_RELOAD = 20

APPS = ["arws", "home-web", "detroit-web", "projetoliteratura-web"]

HOME_MARKER = "ALRI Group | Holding Company"

RESULTS = []


def record(name, ok, detail=""):
    RESULTS.append((name, ok, detail))
    mark = "PASS" if ok else "FAIL"
    print("      [%s] %s%s" % (mark, name, (" - " + detail if detail else "")))
    return ok


# ---------------------------------------------------------------- helpers

def run(cmd):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)


def run_exe(args):
    p = subprocess.run(args, capture_output=True, text=True, timeout=60)
    return p.returncode, p.stdout.strip(), p.stderr.strip()


def alrios(*args):
    code, out, err = run_exe([os.path.join(ARWS, "alrios.exe")] + list(args))
    return code, out


def port_open(port, host="127.0.0.1"):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.5)
    try:
        s.connect((host, port))
        return True
    except OSError:
        return False
    finally:
        s.close()


def wait_port(port, timeout=30):
    t0 = time.time()
    while time.time() - t0 < timeout:
        if port_open(port):
            return True
        time.sleep(0.3)
    return False


def stop_all():
    for name in ("arcore.exe", "node.exe"):
        run("taskkill /f /im %s >nul 2>nul" % name)
    for name in ("home.web.exe", "detroit.web.exe", "projetoliteratura.web.exe",
                 "home_web.exe", "detroit_web.exe", "projetoliteratura_web.exe"):
        run("taskkill /f /im %s >nul 2>nul" % name)
    time.sleep(1.0)


def orphans():
    out = run("tasklist /fi \"IMAGENAME eq arcore.exe\" /fi \"IMAGENAME eq home.web.exe\" /nh")
    procs = run("powershell -NoProfile -Command \"Get-Process arcore,home.web,detroit.web,projetoliteratura -ErrorAction SilentlyContinue | Select-Object -ExpandProperty ProcessName\"")
    return [n for n in procs.stdout.split() if n]


# ---------------------------------------------------------------- ipc

def send_frame(fd, ftype, payload=b""):
    fd.sendall(struct.pack(">IB", len(payload), ftype) + payload)


def recv_frame(fd, timeout=15):
    fd.settimeout(timeout)
    hdr = b""
    while len(hdr) < 5:
        chunk = fd.recv(5 - len(hdr))
        if not chunk:
            return None, None, None
        hdr += chunk
    flen = struct.unpack(">I", hdr[:4])[0]
    ftype = hdr[4]
    body = b""
    while len(body) < flen:
        chunk = fd.recv(flen - len(body))
        if not chunk:
            return None, None, None
        body += chunk
    return flen, ftype, body


def ipc_ctl(ftype, payload=None):
    fd = socket.create_connection(("127.0.0.1", 9600), timeout=10)
    send_frame(fd, ftype, payload.encode() if payload else b"")
    flen, rtype, body = recv_frame(fd)
    fd.close()
    return rtype, (body.decode("utf-8", "ignore") if body else "")


def ipc_query(target, payload):
    fd = socket.create_connection(("127.0.0.1", 9500), timeout=10)
    send_frame(fd, IPC_QUERY, (target + "\n" + payload).encode())
    flen, rtype, body = recv_frame(fd)
    fd.close()
    return rtype, (body.decode("utf-8", "ignore") if body else "")


def ipc_register(payload):
    fd = socket.create_connection(("127.0.0.1", 9500), timeout=10)
    send_frame(fd, IPC_REGISTER, payload.encode())
    flen, rtype, body = recv_frame(fd)
    fd.close()
    return rtype, (body.decode("utf-8", "ignore") if body else "")


def ipc_unregister(payload):
    fd = socket.create_connection(("127.0.0.1", 9500), timeout=10)
    send_frame(fd, IPC_UNREGISTER, payload.encode())
    flen, rtype, body = recv_frame(fd)
    fd.close()
    return rtype, (body.decode("utf-8", "ignore") if body else "")


def http_get(port, path, host):
    conn = http.client.HTTPConnection("127.0.0.1", port, timeout=15)
    conn.request("GET", path, headers={"Host": host})
    r = conn.getresponse()
    body = r.read()
    loc = r.getheader("Location")
    conn.close()
    return r.status, loc, body


def wait_app_state(app, needle, timeout=20):
    t0 = time.time()
    while time.time() - t0 < timeout:
        rtype, out = ipc_ctl(IPC_CTL_LIST)
        if needle in out and app in out:
            return True
        time.sleep(0.5)
    return False


def ensure_app_running(app):
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    if app in out and "RUNNING" not in out:
        ipc_ctl(IPC_CTL_START, app)
        time.sleep(2)
        return True
    return False


# ---------------------------------------------------------------- phases

def phase_build():
    print("[build] cmake --build build --config Release (all targets + packs)...")
    r = run('cmake --build "%s\\build" --config Release' % ROOT)
    if r.returncode != 0:
        print(r.stdout[-2000:])
        return False
    # force fresh extraction of apps (avoids stale arws.arlib cache)
    pf = os.path.join(ARWS, "programfiles")
    if os.path.isdir(pf):
        shutil.rmtree(pf, ignore_errors=True)
    print("[build] programfiles cache cleared for fresh extraction")
    return True


def stage_runtime_dlls():
    """Ensure arcore + spawned apps find their runtime DLLs (OpenSSL etc.).
    Fresh builds don't copy them into arcore/; the exes search their own dir
    and the working directory, so placing them in arcore/ is enough."""
    if not sys.platform.startswith("win"):
        return
    names = ["libssl-3-x64.dll", "libcrypto-3-x64.dll",
             "libgcc_s_seh-1.dll", "libwinpthread-1.dll"]
    candidates = [
        "C:/ProgramData/mingw64/mingw64/opt/bin",
        "C:/ProgramData/mingw64/mingw64/bin",
    ]
    src_dirs = [d for d in candidates if os.path.isdir(d)]
    missing = []
    for n in names:
        dst = os.path.join(ARWS, n)
        if os.path.exists(dst):
            continue
        found = next((d for d in src_dirs if os.path.exists(os.path.join(d, n))), None)
        if found:
            shutil.copy(os.path.join(found, n), dst)
        else:
            missing.append(n)
    if missing:
        print("      (runtime DLLs not staged: %s)" % ", ".join(missing))


def phase_prepare():
    print("[prep] switching arws.cfg to TEST mode (8080)...")
    stage_runtime_dlls()
    os.makedirs(os.path.dirname(CFG), exist_ok=True)
    if os.path.exists(CFG):
        shutil.copy(CFG, BAKCFG)
    with open(CFG, "w", encoding="utf-8") as f:
        f.write(TEST_CFG_CONTENT)

    if os.path.exists(AUTOSTART):
        shutil.copy(AUTOSTART, BAK_AUTOSTART)


def phase_start():
    print("[start] spawning arcore (background, no console)...")
    flags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    logf = open(LOG, "wb")
    proc = subprocess.Popen(
        [os.path.join(ARWS, "arcore.exe")],
        cwd=ARWS, stdout=logf, stderr=subprocess.STDOUT, creationflags=flags)
    print("      arcore pid=%d" % proc.pid)

    ok_gw = wait_port(8080, 30)
    ok_adm = wait_port(9500, 30)
    ok_ctl = wait_port(9600, 30)
    ok_home = wait_port(3001, 20)
    ok_det = wait_port(3004, 20)
    ok_proj = wait_port(3003, 20)
    print("      gateway 8080=%s admin 9500=%s ctl 9600=%s home=3001=%s det=3004=%s proj=3003=%s"
          % (ok_gw, ok_adm, ok_ctl, ok_home, ok_det, ok_proj))
    return proc


def tail_log(n=30):
    try:
        with open(LOG, "r", encoding="utf-8", errors="replace") as f:
            for ln in f.readlines()[-n:]:
                print("      " + ln.rstrip())
    except Exception as e:
        print("      (log read error: %s)" % e)


# ---------------------------------------------------------------- tests

def test_f1():
    print("[F1] control channel 9600 + loader lifecycle...")
    rtype, out = ipc_ctl(IPC_CTL_PING)
    record("F1 ping", rtype == IPC_RESPONSE, "rtype=%s out=%s" % (rtype, out))

    rtype, out = ipc_ctl(IPC_CTL_LIST)
    ok = rtype == IPC_RESPONSE and all(a in out for a in APPS)
    record("F1 list (4 apps)", ok, out.replace("\n", " | "))

    rtype, out = ipc_ctl(IPC_CTL_STOP, "home-web")
    record("F1 stop home-web", rtype == IPC_RESPONSE, out)
    time.sleep(1)
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    record("F1 home-web stopped", "STOPPED" in out and "home-web" in out)

    rtype, out = ipc_ctl(IPC_CTL_START, "home-web")
    record("F1 start home-web", rtype == IPC_RESPONSE, out)
    time.sleep(1.5)
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    record("F1 home-web running again", "RUNNING" in out and "home-web" in out)

    rtype, out = ipc_ctl(IPC_CTL_RESTART, "home-web")
    record("F1 restart home-web", rtype == IPC_RESPONSE, out)
    time.sleep(1.5)
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    record("F1 home-web after restart", "RUNNING" in out and "home-web" in out)


def test_f2():
    print("[F2] autostart.cfg filtering...")
    with open(AUTOSTART, "w", encoding="utf-8") as f:
        f.write("home-web\n")
    rtype, out = ipc_ctl(IPC_CTL_POWER_RELOAD)
    record("F2 power reload", rtype == IPC_RESPONSE, out)
    time.sleep(5)

    ok = wait_app_state("home-web", "RUNNING")
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    det_stopped = ("detroit-web" in out and "STOPPED" in out)
    proj_stopped = ("projetoliteratura-web" in out and "STOPPED" in out)
    home_run = ("home-web" in out and "RUNNING" in out)
    record("F2 only home-web RUNNING (det/proj STOPPED)",
           home_run and det_stopped and proj_stopped, out.replace("\n", " | "))

    with open(AUTOSTART, "w", encoding="utf-8") as f:
        f.write("arws\nhome-web\ndetroit-web\nprojetoliteratura-web\n")
    ipc_ctl(IPC_CTL_POWER_RELOAD)
    time.sleep(5)
    rtype, out = ipc_ctl(IPC_CTL_LIST)
    all_run = all(a in out and "RUNNING" in out for a in APPS)
    record("F2 all RUNNING after restore", all_run, out.replace("\n", " | "))


def test_f3():
    print("[F3] CLI alrios...")
    code, out = alrios("list")
    record("F3 alrios list", code == 0 and all(a in out for a in APPS), out)

    code, out = alrios("start", "add", "home-web")
    with open(AUTOSTART, "r", encoding="utf-8") as f:
        content = f.read()
    record("F3 start add home-web", code == 0 and "home-web" in content, out + " / cfg: " + content.replace("\n", ","))

    code, out = alrios("start", "del", "home-web")
    with open(AUTOSTART, "r", encoding="utf-8") as f:
        content = f.read()
    record("F3 start del home-web", code == 0 and "home-web" not in content, out)

    code, out = alrios("stop", "home-web")
    time.sleep(1)
    code2, out2 = alrios("list")
    record("F3 CLI stop home-web", code == 0 and "STOPPED" in out2, out)

    code, out = alrios("start", "home-web")
    time.sleep(1.5)
    code2, out2 = alrios("list")
    record("F3 CLI start home-web", code == 0 and "RUNNING" in out2, out)

    code, out = alrios("restart", "home-web")
    time.sleep(1.5)
    code2, out2 = alrios("list")
    record("F3 CLI restart home-web", code == 0 and "RUNNING" in out2, out)

    code, out = alrios("start", "add", "home-web")
    with open(AUTOSTART, "r", encoding="utf-8") as f:
        content = f.read()
    record("F3 start add home-web (restore)", code == 0 and "home-web" in content, out)

    code, out = alrios("power", "reload")
    record("F3 power reload via CLI", code == 0, out)
    time.sleep(5)


def test_f4():
    print("[F4] app/gateway queries...")
    for app in ("home-web", "detroit-web", "projetoliteratura-web"):
        ensure_app_running(app)
        rtype, out = ipc_query(app, "status")
        record("F4 %s status" % app, rtype == IPC_QUERY_RESP and "RUNNING" in out, out)
        rtype, out = ipc_query(app, "ping")
        record("F4 %s ping" % app, rtype == IPC_QUERY_RESP and out.replace("\x00", "").strip() == "pong", out)
        rtype, out = ipc_query(app, "routes")
        record("F4 %s routes" % app, rtype == IPC_QUERY_RESP and "proxy=http" in out, out[:80])

    rtype, out = ipc_query("arws", "status")
    record("F4 arws status", rtype == IPC_QUERY_RESP and "arws RUNNING" in out, out)
    rtype, out = ipc_query("arws", "ping")
    record("F4 arws ping", rtype == IPC_QUERY_RESP and out.replace("\x00", "").strip() == "pong", out)
    rtype, out = ipc_query("arws", "routes")
    record("F4 arws routes", rtype == IPC_QUERY_RESP and "stream" in out, out[:80])
    rtype, out = ipc_query("arws", "cfg reload")
    record("F4 arws cfg reload", rtype == IPC_QUERY_RESP and "reloaded" in out, out)
    rtype, out = ipc_query("arws", "maintenance alrigroup.com")
    record("F4 arws override host", rtype == IPC_QUERY_RESP and "override" in out, out)
    rtype, out = ipc_query("arws", "production alrigroup.com")
    record("F4 arws override revert", rtype == IPC_QUERY_RESP, out)
    rtype, out = ipc_query("arws", "production")
    record("F4 arws global production", rtype == IPC_QUERY_RESP and "global mode -> production" in out, out)
    rtype, out = ipc_query("arws", "test")
    record("F4 arws global test", rtype == IPC_QUERY_RESP and "global mode -> test" in out, out)
    rtype, out = ipc_query("arws", "production")
    record("F4 arws global back to production", rtype == IPC_QUERY_RESP, out)


def test_http():
    print("[HTTP] gateway checks on 8080 (TEST mode)...")
    try:
        st, _, body = http_get(8080, "/", "alrigroup.com")
        ok = st == 200 and HOME_MARKER in body.decode("utf-8", "ignore")
        record("HTTP home-web Host alrigroup.com", ok, "status=%d marker=%s" % (st, HOME_MARKER in body.decode("utf-8", "ignore")))
    except Exception as e:
        record("HTTP home-web Host alrigroup.com", False, str(e))

    try:
        st, _, body = http_get(8080, "/", "localhost")
        ok = st == 200 and HOME_MARKER in body.decode("utf-8", "ignore")
        record("HTTP home-web Host localhost", ok, "status=%d marker=%s" % (st, HOME_MARKER in body.decode("utf-8", "ignore")))
    except Exception as e:
        record("HTTP home-web Host localhost", False, str(e))

    try:
        st, _, body = http_get(8080, "/", "detroitgg.alrigroup.com")
        record("HTTP detroit Host detroitgg", st == 200 and len(body) > 0, "status=%d len=%d" % (st, len(body)))
    except Exception as e:
        record("HTTP detroit Host detroitgg", False, str(e))

    try:
        st, _, body = http_get(8080, "/projetoliteratura", "alexsander.alrigroup.com")
        record("HTTP projetoliteratura", st == 200 and len(body) > 0, "status=%d len=%d" % (st, len(body)))
    except Exception as e:
        record("HTTP projetoliteratura", False, str(e))


def test_f5():
    print("[F5] armake buildapp + redirect 302...")
    tmp = os.path.join(os.environ["TEMP"], "opencode", "suite_buildapp")
    if os.path.isdir(tmp):
        shutil.rmtree(tmp, ignore_errors=True)
    os.makedirs(tmp)
    staging = os.path.join(ARWS, ".staging", "home.web")
    code, out, err = run_exe([os.path.join(ARWS, "armake.exe"), "buildapp", "-s", staging, "-o", tmp])
    outfile = os.path.join(tmp, "home-web.arapp")
    ok = code == 0 and os.path.isfile(outfile)
    record("F5 buildapp -s/-o", ok, "%s -> %s" % (staging, outfile))

    code, out, err = run_exe([os.path.join(ARWS, "armake.exe"), "list", outfile])
    record("F5 buildapp valid .arapp", code == 0 and "home.web.arappmake" in out and "home.web.exe" in out, out[:100])

    tmp2 = os.path.join(os.environ["TEMP"], "opencode", "suite_buildapp2")
    if os.path.isdir(tmp2):
        shutil.rmtree(tmp2, ignore_errors=True)
    os.makedirs(tmp2)
    target = os.path.join(tmp2, "custom.arapp")
    code, out, err = run_exe([os.path.join(ARWS, "armake.exe"), "buildapp", "-s", staging, "-o", target])
    record("F5 buildapp -o file.arapp", code == 0 and os.path.isfile(target), target)

    # redirect via gateway register + HTTP 302
    rtype, ack = ipc_register("suite-redir /old GET redirect.test stream type=redirect redirect=http://alrigroup.com/new")
    record("F5 redirect register", rtype == IPC_ACK and "REDIRECT" in ack, ack)
    time.sleep(0.5)
    try:
        st, loc, body = http_get(8080, "/old", "redirect.test")
        ok = st == 302 and loc == "http://alrigroup.com/new"
        record("F5 redirect 302", ok, "status=%d location=%s" % (st, loc))
    except Exception as e:
        record("F5 redirect 302", False, str(e))
    rtype, ack = ipc_unregister("/old GET redirect.test")
    record("F5 redirect unregister", rtype == IPC_ACK, ack)


def cleanup(proc):
    if proc and proc.poll() is None:
        try:
            proc.terminate()
        except Exception:
            pass
    time.sleep(1)
    stop_all()
    time.sleep(1)
    if os.path.exists(BAKCFG):
        shutil.copy(BAKCFG, CFG)
        print("      production arws.cfg restored")
    elif os.path.exists(CFG):
        os.remove(CFG)
    if os.path.exists(BAK_AUTOSTART):
        shutil.copy(BAK_AUTOSTART, AUTOSTART)
        print("      autostart.cfg restored")
    rest = orphans()
    if rest:
        print("      WARNING: orphan processes: %s" % rest)


def main():
    print("== ALRIOS test suite (F1-F5) ==")
    no_build = "--no-build" in sys.argv
    proc = None
    try:
        if not no_build:
            print("[0/7] building...")
            if not phase_build():
                print("RESULT: BUILD FAILED")
                return 1
        else:
            print("[0/7] build skipped (--no-build)")

        print("[1/7] stopping old processes...")
        stop_all()
        time.sleep(1)

        print("[2/7] preparing TEST config...")
        phase_prepare()

        print("[3/7] starting arcore...")
        proc = phase_start()
        if not wait_port(9500, 10):
            print("      FAILED to start services; log tail:")
            tail_log()
            return 1

        print("[4/7] F1 control channel...")
        test_f1()

        print("[5/7] F2 autostart + F3 CLI + F4 queries...")
        test_f2()
        test_f3()
        test_f4()
        test_http()
        test_f5()

        print("[6/7] summary...")
        passed = sum(1 for _, ok, _ in RESULTS if ok)
        failed = sum(1 for _, ok, _ in RESULTS if not ok)
        for name, ok, detail in RESULTS:
            print("      %s %s%s" % ("PASS" if ok else "FAIL", name, (" - " + detail if detail else "")))
        print("      passed=%d failed=%d total=%d" % (passed, failed, passed + failed))

        print("[7/7] cleanup...")
        cleanup(proc)
        proc = None
        print()
        if failed:
            print("RESULT: SOME TESTS FAILED")
            return 1
        print("RESULT: ALL TESTS PASSED")
        return 0
    finally:
        if proc is not None:
            cleanup(proc)


if __name__ == "__main__":
    sys.exit(main())
